# This template will build and test your Java projects using Apache Ant.
# For general Ant build and test information see: https://ant.apache.org/manual/

# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is analogous to the Maven template but adapted for Ant usage.

variables:
  ANT_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Djava.awt.headless=true

# Ant does not use a project-specific repository like Maven's .m2, but you can still cache
# directories if needed (e.g., custom lib directories or directories holding dependencies).
cache:
  paths:
    - lib/
    - build/

# Use a Docker image that has Java and Ant installed.
# For Docker image tags see https://hub.docker.com/_/openjdk or other images that include Ant and JDK.
image: frekele/ant:1.10.5-jdk11

# Build
build-job:
  stage: build
  script:
    - ant compile
  artifacts:
    paths:
      - build/

# Test
test-job:
  stage: test
  script:
    - ant test
  artifacts:
    reports:
    junit:
      - test-results/**/*.xml

# The example assumes there's an existing build.xml that defines 'compile' and 'test' targets.
# Make sure your build.xml is properly configured to handle these commands.
