image: ubuntu:20.04

stages:
  - setup
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/

setup_dependencies:
  stage: setup
  script:
    - ant download
  artifacts:
    paths:
      - lib/

build_game:
  stage: build
  script:
    - ant compile
    - ant jar
  artifacts:
    paths:
      - build/
      - dist/

test_model:
  stage: test
  script:
    - ant test
  artifacts:
    reports:
      junit: test-results/**/*.xml
