image: frekele/ant:1.10.1-jdk8

stages:
  - build
  - test

cache:
  paths:
    - .ant-cache

before_script:
  - export ANT_HOME="/usr/share/ant"
  - export PATH="$ANT_HOME/bin:$PATH"
  - export ANT_OPTS="-Dant.cache.enabled=true -Duser.home=.ant-cache"

build:
  stage: build
  script:
    - ant compile

test:
  stage: test
  script:
    - ant test