image: ubuntu:20.04

stages:
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant junit4

# Build
build_game:
  stage: build
  script:
    - ant compile -lib lib
    - ant jar -lib lib

# Test
test_model:
  stage: test
  script:
    - >
      ant test -lib lib
      -Dlibs.junit_4.classpath=/usr/share/java/junit4.jar
      -Dlibs.hamcrest.classpath=/usr/share/java/hamcrest-core.jar