image: ubuntu:20.04

stages:
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant junit4
  - wget -P lib/ http://central.maven.org/maven2/junit/junit/4.13/junit-4.13.jar
  - wget -P lib/ http://central.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

# Build
build_game:
  stage: build
  script:
    - ant compile -lib lib
    - ant jar -lib lib

# Test
test_model:
  stage: test
  script:
    - ant test -lib lib
