# This CI configuration is for building and testing Java applications using Apache Ant on GitLab CI/CD.

stages:
  - build
  - test

before_script:
  # Prepare the system and install necessary packages
  - apt-get update -yqq
  - apt-get install -yqq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant junit4

image: ubuntu:20.04

# Cache dependencies to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/
    - build/

# Build stage: compiles the source code and builds the JAR file
build_game:
  stage: build
  script:
    - ant compile -lib lib
    - ant jar -lib lib
  artifacts:
    paths:
      - build/
      - dist/

# Test stage: executes tests and generates test reports
test_model:
  stage: test
  script:
    - ant test -lib lib
  artifacts:
    reports:
      junit: test-results/**/*.xml

# Ensuring that the build.xml file in your repository properly defines 'compile', 'jar', and 'test' targets.
