image: ubuntu:20.04
# This CI configuration is for building and testing Java applications using Apache Ant on GitLab CI/CD.

stages:
  - build
  - test

before_script:
  # Prepare the system and install necessary packages
  - apt-get update -yqq
  - apt-get install -yqq software-properties-common
  - add-apt-repository -y ppa:openjdk-r/ppa
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk
  - wget -O lib/junit.jar https://repo1.maven.org/maven2/junit/junit/4.13/junit-4.13.jar
  - wget -O lib/hamcrest-core.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar


# Build stage: compiles the source code and builds the JAR file
build_game:
  stage: build
  script:
    - ant compile -lib lib
    - ant jar -lib lib
  artifacts:
    paths:
      - build/
      - dist/

# Test stage: executes tests and generates test reports
test_model:
  stage: test
  script:
    - ant test -lib lib
  artifacts:
    reports:
      junit: test-results/**/*.xml
